### ISSUE TITLE
How to use my own model in the sagemaker

### ISSUE THREAD

**Issue by lijoe123** [aws-samples/host-yolov8-on-sagemaker-endpoint#23]
How to use my own model in the sagemaker? I don't know how to use my own model in the sagemaker, and it occur error

**Comment by shahromil16** [comment]
@lijoe123 
This repository is solely focused on hosting YOLOv8 model on SageMaker endpoint. However for hosting any other custom model, follow AWS documentations. 
For example: https://docs.aws.amazon.com/sagemaker/latest/dg/docker-containers-notebooks.html
