### ISSUE TITLE
nodejs12.x is no longer supported for creating or updating AWS Lambda functions

### ISSUE THREAD

**Issue by migu0** [aws-samples/host-yolov8-on-sagemaker-endpoint#9]
Hi @kcsong and @rpshah,

Thanks a lot for this script. I got the following error when clicking on your "Launch stack" button on N. Virginia region:

`CustomS3AutoDeleteObjectsCustomResourceProviderHandler`

`Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 42532834-d584-4dae-8feb-8827ed878a0e)" (RequestToken: ec4fa608-8ac9-5375-8694-db3f03b8e431, HandlerErrorCode: InvalidRequest)`

<img width="832" alt="Screenshot 2023-07-18 at 6 38 18 pm" src="https://github.com/aws-samples/host-yolov8-on-sagemaker-endpoint/assets/430682/c97cb0f8-baa8-45e5-9312-f68d0d948dcb">

Any chance this can be updated so that I can re run?

Thank you,
Michael

**Comment by KaramRazooq** [comment]
I faced this issue as well, you can just use nodejs16.x instead!

**Comment by simongle** [comment]
@migu0 In order to achieve this, I bumped the version in `yolov8-pytorch-cdk/requirements.txt`:
```
aws-cdk-lib==2.22.0 -> 2.28.0
```
which seemed to fix it for me, they [apparently](https://stackoverflow.com/questions/76347015/the-runtime-parameter-of-nodejs12-x-is-no-longer-supported-for-creating-or-updat) upgraded the node version to sixteen in the cdk 2.28.0 release

**Comment by boxraw-tech** [comment]
Tried this fix and got `nodejs14.x is no longer supported`. So you need to work out what the latest workable release is. [This page](https://github.com/aws/aws-cdk/releases) contains all the `aws-cdk` releases. You could go with the latest one (at the time of writing that's 2.131.0) however I was a bit concerned about the upgrade to python3.12 so landed on 2.96.0 which includes an upgrade to nodejs.18 for lambda. YMMV.
